### PR TITLE
Commiting Class2 to BranchX

### PR DESCRIPTION
**Pull request by GaddamNagarjuna9595**
hi Avinash
i have committed class2.Please review and approve
Regards
Nagarjuna.

### CODE REVIEW

**Comment by NasinaAvinash** [comment]
Hi naga, 
 your code looks good please add one more check 

regards,
avi\

**Comment by NasinaAvinash** [comment]
Hi naga,
 Now its looking pretty good 
The code was Approved.
enjoy Pandagow.

**Comment by GaddamNagarjuna9595** [comment]
Hi Avi ,
code sexy,Approved.....

**Comment by NasinaAvinash** [comment]
Thanks Namsthy

**Pull request merged**
